function [df] = convertCells2Python(Datastore)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

% convert to table
df = cell2table(Datastore);

df = renamevars(df,["Datastore1","Datastore2","Datastore3","Datastore4","Datastore5","Datastore6","Datastore7", ...
    "Datastore8","Datastore9","Datastore10","Datastore11","Datastore12","Datastore13","Datastore14","Datastore15","Datastore16", ...
    "Datastore17","Datastore18","Datastore19","Datastore20","Datastore21","Datastore22","Datastore23","Datastore24","Datastore25", ...
    "Datastore26","Datastore27","Datastore28","Datastore29","Datastore30","Datastore31","Datastore32","Datastore33","Datastore34", ...
    "Datastore35","Datastore36","Datastore37","Datastore38","Datastore39","Datastore40","Datastore41","Datastore42","Datastore43","Datastore44", ...
    "Datastore45","Datastore46","Datastore47","Datastore48","Datastore49","Datastore50","Datastore51","Datastore52","Datastore53","Datastore54","Datastore55", ...
    "Datastore56","Datastore57","Datastore58","Datastore59","Datastore60"], ...
    ["session_id","session_date","paradigm","phase","sequential_session_number","sequential_trial_number","ISI", ...
    "trial_onset_time","stimulus_time","stimulus_strength","lick_times","response_time","go_nogo","response_delayed","categorical_outcome","previos_trial_categorical_outcome", ...
    "time_btwn_onset_stim","distractor_times","photometry_region_ch1","photometry_5pctl_ch1","photometry_95pctl_ch1","photometry_region_ch2","photometry_5pctl_ch2","photometry_95pctl_ch2","optogenetic_manipulation_tag", ...
    "chemo_pharm_manipulation_tag","chemo_pharm_dosage","baseline_pupil_window","pupil_base_before_onset","pupil_base_before_stimulus","pupil_area","pupil_5pctl","pupil_95pctl","window_photo_base", ...
    "photo_base_before_onset_ch1","photo_base_before_stim_ch1","photometry_ch1","photo_base_before_onset_ch2","photo_base_before_stim_ch2","photometry_ch2","whisker_rad","wheel_displacement","opto_pulse_times","opto_power_frequency", ...
    "fsAP","fsLF","LFP_data","spike_times","spike_cluster_group","spike_cluster_amplitudes","spike_cluster_centroids","spike_cluster_waveforms","stimulus_index_AP","stimulus_index_LF","total_session_time_lag_NI_xPC","pscho_curve","dPrime","criterion", ...
    "Datastore59","Datastore60"]);


end